<div class="space-y-6">
    @if (session('success'))<div class="rounded-lg bg-green-50 px-4 py-3 text-sm font-medium text-green-800">{{ session('success') }}</div>@endif
    @if (session('clock_success'))<div class="rounded-lg bg-blue-50 px-4 py-3 text-sm font-medium text-blue-800">{{ session('clock_success') }}</div>@endif

    <section class="card p-6">
        <div class="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><h2 class="text-xl font-bold text-gray-800">My staff attendance</h2><p class="mt-1 text-sm text-gray-500">Your attendance is recorded independently from learner attendance. An approved school network can clock you in automatically; location sharing is optional.</p></div><div class="rounded-lg px-3 py-2 text-sm font-semibold {{ $staffAttendance?->clock_in_at ? 'bg-green-50 text-green-800' : 'bg-amber-50 text-amber-800' }}">{{ $staffAttendance?->clock_in_at ? 'Clocked in' : 'Not clocked in' }}</div></div>
        @if($locationSettings['automatic_enabled'])<p class="mt-4 rounded-lg bg-blue-50 px-3 py-2 text-sm text-blue-800">Automatic clock-in is enabled for approved school IP addresses. {{ $autoClockedIn ? 'Your approved network was verified and your clock-in was recorded.' : 'If this network is not approved, use the manual option below.' }}</p>@endif
        <div class="mt-5 flex flex-wrap items-center gap-3" x-data="{ submit(action) { if (!navigator.geolocation) { $wire[action](); return; } navigator.geolocation.getCurrentPosition((position) => { $wire.set('latitude', position.coords.latitude); $wire.set('longitude', position.coords.longitude); $wire[action](); }, () => $wire[action](), { enableHighAccuracy: true, timeout: 8000, maximumAge: 60000 }); } }">
            @if(! $staffAttendance?->clock_in_at)<button type="button" x-on:click="submit('clockIn')" class="rounded-lg bg-green-700 px-5 py-2.5 text-sm font-semibold text-white">Clock in</button>@elseif(! $staffAttendance?->clock_out_at)<span class="text-sm text-gray-600">Clocked in at <strong>{{ $staffAttendance->clock_in_at->format('H:i') }}</strong> via {{ str_replace('_', ' ', $staffAttendance->clock_in_method) }}.</span><button type="button" x-on:click="submit('clockOut')" class="rounded-lg border border-red-300 px-5 py-2.5 text-sm font-semibold text-red-700">Clock out</button>@else<span class="text-sm text-gray-600">Clocked in {{ $staffAttendance->clock_in_at->format('H:i') }} · clocked out {{ $staffAttendance->clock_out_at->format('H:i') }}.</span>@endif
        </div>
    </section>

    <section class="card p-6">
        <div class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 class="text-xl font-bold text-gray-800">Class learner attendance</h2><p class="mt-1 text-sm text-gray-500">Only your assigned class can be recorded. Set each learner manually, or start with bulk Present and adjust exceptions before confirming.</p></div>@if($register)<button type="button" wire:click="markAllPresent" class="rounded-lg border border-green-300 px-4 py-2 text-sm font-semibold text-green-700">Mark all present</button>@endif</div>
        @if($classes->isEmpty())<div class="mt-5 rounded-lg bg-amber-50 px-4 py-3 text-sm text-amber-800">You are not assigned as a class teacher yet. Ask a school administrator to assign you to a class before recording learner attendance.</div>@else
            <div class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3"><label><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Class</span><select wire:model.live="classId" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm">@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}{{ $class->stream ? ' ' . $class->stream : '' }}</option>@endforeach</select></label><label><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Attendance date</span><input type="date" max="{{ today()->toDateString() }}" wire:model.live="attendanceDate" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label></div>
            @if($register)<div class="mt-5 overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-3 py-3">Learner</th><th class="px-3 py-3">Admission no.</th><th class="px-3 py-3">Status</th><th class="px-3 py-3">Remark</th></tr></thead><tbody class="divide-y divide-gray-100">@foreach($register as $learnerId => $entry)<tr><td class="px-3 py-3 font-medium text-gray-800">{{ $entry['name'] }}</td><td class="px-3 py-3 text-gray-500">{{ $entry['admission_number'] }}</td><td class="px-3 py-3"><select wire:model="register.{{ $learnerId }}.status" class="rounded-lg border border-gray-300 px-2 py-2 text-sm"><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></td><td class="px-3 py-3"><input wire:model="register.{{ $learnerId }}.remarks" maxlength="500" class="w-full rounded-lg border border-gray-300 px-2 py-2 text-sm" placeholder="Optional"></td></tr>@endforeach</tbody></table></div><div class="mt-5 flex items-center gap-3"><button wire:click="saveRegister" class="rounded-lg bg-green-700 px-5 py-2.5 text-sm font-semibold text-white">Confirm and submit attendance</button><span class="text-xs text-gray-500">This saves the full-day register for {{ \Carbon\Carbon::parse($attendanceDate)->format('d M Y') }}.</span></div>@else<div class="mt-5 rounded-lg bg-gray-50 px-4 py-5 text-sm text-gray-500">There are no active learners in this class.</div>@endif
        @endif
    </section>
</div>
